#!/bin/bash

set -e


fg_black="$(tput setaf 0)"
fg_red="$(tput setaf 1)"
fg_green="$(tput setaf 2)"
fg_yellow="$(tput setaf 3)"
fg_blue="$(tput setaf 4)"
fg_magenta="$(tput setaf 5)"
fg_cyan="$(tput setaf 6)"
fg_white="$(tput setaf 7)"
reset="$(tput sgr0)"


create_pi_release () {
  echo "${fg_magenta}Creating armv7 release (PI)${fg_reset}"

  echo "${fg_magenta}Creating 'releases/release-raspberrypi3' ${fg_reset}"
  mkdir -p releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'bin/friday-armv7-unknown-linux-gnueabinhf' 'releases/release-raspberrypi3' ${fg_reset}"
  cp bin/friday-armv7-unknown-linux-gnueabinhf releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'releases/platform.pi/*' 'releases/release-raspberrypi3' ${fg_reset}"
  cp releases/platform.pi/* releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'releases/platform.common/*.json' 'releases/release-raspberrypi3' ${fg_reset}"
  cp releases/platform.common/*.json releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'releases/platform.common/models' 'releases/release-raspberrypi3' ${fg_reset}"
  cp -r releases/platform.common/models releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'releases/platform.common/discovery' 'releases/release-raspberrypi3' ${fg_reset}"
  cp -r releases/platform.common/discovery releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'friday/friday-vendor/vendor-scripts/test-resources/scripts' 'releases/release-raspberrypi3' ${fg_reset}"
  cp -r friday/friday-vendor/vendor-scripts/test-resources/scripts releases/release-raspberrypi3

  echo "${fg_magenta}Copying 'web/becky/release/' 'releases/release-raspberrypi3/' ${fg_reset}"
  cp -r web/becky/release releases/release-raspberrypi3

  GUI_DIR=releases/release-raspberrypi3/becky
  if [ -d "$GUI_DIR" ]; then rm -Rf $GUI_DIR; fi

  echo "${fg_magenta}Renaming 'releases/release-raspberrypi3/release' '$GUI_DIR'${fg_reset}"
  mv releases/release-raspberrypi3/release $GUI_DIR

  echo "${fg_magenta}Creating 'releases/release-raspberrypi3/recordings' '${fg_reset}"
  mkdir -p releases/release-raspberrypi3/recordings


  echo "${fg_green}Release successful! Release should be in releases/release-raspberrypi3! :) ${fg_reset}"
} 

create_linux_release () {
  echo "${fg_magenta}Creating linux x86_64 release ${fg_reset}"

  echo "${fg_magenta}Creating 'releases/release-linux' ${fg_reset}"
  mkdir -p releases/release-linux

  echo "${fg_magenta}Copying 'bin/friday-x86_64-unknown-linux-gnu' 'releases/release-linux' ${fg_reset}"
  cp bin/friday-x86_64-unknown-linux-gnu releases/release-linux

  echo "${fg_magenta}Copying 'releases/platform.li/*' 'releases/release-linux' ${fg_reset}"
  cp releases/platform.li/* releases/release-linux

  echo "${fg_magenta}Copying 'releases/platform.common/*.json' 'releases/release-linux' ${fg_reset}"
  cp releases/platform.common/*.json releases/release-linux

  echo "${fg_magenta}Copying 'releases/platform.common/models' 'releases/release-linux' ${fg_reset}"
  cp -r releases/platform.common/models releases/release-linux

  echo "${fg_magenta}Copying 'releases/platform.common/discovery' 'releases/release-linux' ${fg_reset}"
  cp -r releases/platform.common/discovery releases/release-linux

  echo "${fg_magenta}Copying 'friday/friday-vendor/vendor-scripts/test-resources/scripts' 'releases/release-linux' ${fg_reset}"
  cp -r friday/friday-vendor/vendor-scripts/test-resources/scripts releases/release-linux

  echo "${fg_magenta}Copying 'web/becky/release/' 'releases/release-linux/' ${fg_reset}"
  cp -r web/becky/release releases/release-linux

  GUI_DIR=releases/release-linux/becky
  if [ -d "$GUI_DIR" ]; then rm -Rf $GUI_DIR; fi

  echo "${fg_magenta}Renaming 'releases/release-linux/release' '$GUI_DIR'${fg_reset}"
  mv releases/release-linux/release $GUI_DIR

  echo "${fg_magenta}Creating 'releases/release-linux/recordings' '${fg_reset}"
  mkdir -p releases/release-linux/recordings


  echo "${fg_green}Release successful! Release should be in releases/release-linux! :) ${fg_reset}"


}

print_help() {
  echo ""
  echo ""
  echo "${fg_green}  ******** Friday release script ******** ${fg_black}"
  echo " "
  echo "${fg_white} options:"
  echo "-h, --help  show brief help"
  echo "${fg_magenta}-pi --armv7-unknown-linux-gnueabinhf${fg_white},   E.g Raspberry Pi (2, 3..)s"
  echo "${fg_magenta}-li --x86_64-unknown-linux-gnu${fg_white},  Common Desktops and laptops (running linux)"
  exit 0
}


#while test $# -gt 0; do
case "$1" in
  -h|--help)
    print_help
    break
    ;;
  --armv7-unknown-linux-gnueabinhf)
    create_pi_release
    exit 0
    ;;
  -pi)
    create_pi_release
    exit 0
    ;;
  --friday-x86_64-unknown-linux-gnu)
    create_linux_release
    exit 0
    ;;
  -li)
    create_linux_release
    exit 0
    ;;
  *)
    print_help
    break
    ;;
esac
#done
print_help
